sonar.projectKey=setia141_claude-skills-to-adk-agent
sonar.organization=setia141-1
sonar.sources=.
sonar.exclusions=venv/**,adk_chroma_db/**,sessions/**,output/**,**/__pycache__/**,*.pyc
sonar.python.version=3.11
sonar.host.url=https://sonarcloud.io
